src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{

    /**
     * Many Users have Many Groups.
     * @@ORM\ManyToMany(targetEntity="ParticipantE")
     * @ORM\JoinTable(name="ParticipationE",
     *      joinColumns={@ORM\JoinColumn(name="id_evenement", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="id_participant", referencedColumnName="id")}
     *      )
     */
    private $events;

    // ...

    public function __construct() {
        $this->events = new ArrayCollection();
        $this->eventlikes = new ArrayCollection();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
    /*
     * @ORM\Column(type="string")
     */
    private $picture;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $localitation;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_societe;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Viewed;

    /**
     * @ORM\OneToMany(targetEntity=Eventlikes::class, mappedBy="event" )
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $eventlikes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    public function getDateAt(): ?\DateTimeInterface
    {
        return $this->dateAt;
    }

    public function setDateAt(\DateTimeInterface $dateAt): self
    {
        $this->dateAt = $dateAt;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setPicture($picture)
    {
        $this->picture = $picture;

        return $this;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLocalitation(): ?string
    {
        return $this->localitation;
    }

    public function setLocalitation(string $localitation): self
    {
        $this->localitation = $localitation;

        return $this;
    }

    public function getIdSociete(): ?int
    {
        return $this->id_societe;
    }

    public function setIdSociete(int $id_societe): self
    {
        $this->id_societe = $id_societe;

        return $this;
    }

    public function getViewed(): ?int
    {
        return $this->Viewed;
    }

    public function setViewed(?int $Viewed): self
    {
        $this->Viewed = $Viewed;

        return $this;
    }

    public function __toString()
    {
        return $this->type;
    }

    /**
     * @return Collection|Eventlikes[]
     */
    public function getEventlikes(): Collection
    {
        return $this->eventlikes;
    }

    public function addEventlike(Eventlikes $eventlike): self
    {
        if (!$this->eventlikes->contains($eventlike)) {
            $this->eventlikes[] = $eventlike;
            $eventlike->setEvent($this);
        }

        return $this;
    }

    public function removeEventlike(Eventlikes $eventlike): self
    {
        if ($this->eventlikes->removeElement($eventlike)) {
            // set the owning side to null (unless already changed)
            if ($eventlike->getEvent() === $this) {
                $eventlike->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @param ParticipantE $participantE
     * @return bool
     */
    public function  isLikedByUser(ParticipantE $participantE) : bool{
        foreach ($this->eventlikes as $eventlike){
            if($eventlike->getUser() == $participantE) return false;
        }
        return false;

    }


}

src/Controller/EvenementSocieteController.php
<?php


namespace App\Controller;

use App\Entity\Eventlikes;
use App\Entity\NotifEvent;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Evenement;
use App\Entity\ParticipantE;
use App\Entity\ParticipationE;
use App\Form\EventType;
use App\Repository\EvenementRepository;
use Doctrine\Persistence\ObjectManager;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncode;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;
use Symfony\Component\Serializer\Normalizer\NormalizableInterface;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Validator\Constraints\DateTime;

class EvenementSocieteController extends AbstractController
{
    /**
     * @param $uid
     * @param $eid
     * @return Response
     * @Route ("/like{uid}/{eid}" , name="like")
     */
    public function like($uid,$eid):Response{


        $rep=$this->getDoctrine()->getRepository(Eventlikes::class);
        $repu=$this->getDoctrine()->getRepository(ParticipantE::class);
        $repe=$this->getDoctrine()->getRepository(Evenement::class);
        $entityManager = $this->getDoctrine()->getManager();

        $user = $repu->find($uid);
        $event = $repe->find($eid);

        $like = $rep->findOneBy([
                'user' => $uid ,
                'event' => $eid
        ]);

        if(!empty($like)){
            $entityManager->remove($like);
            $entityManager->flush();

            return $this->json([
                'code' => 200 ,
                'message' => 'like bien supprimer',
                'likes' => $rep->count(['event' => $event])
            ],200);

        }else{
            $like = new Eventlikes();
            $like->setUser($user)
                ->setEvent($event);

            $entityManager->persist($like);
            $entityManager->flush();
            return $this->json([
                'code' => 200 ,
                'message' => 'like bien ajouter',
                'likes' => $rep->count(['event' => $event])
            ],200);
        }
    }

    /**
     * @Route("/pdf{id}", name="pdf")
     */
    public function pdf(int $id): Response
    {

        $rep=$this->getDoctrine()->getRepository(Evenement::class);
        $evenement=$rep->find($id);

        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        $dompdf = new Dompdf($pdfOptions);

        $html = $this->renderView('evenement_societe/eventmail.html.twig', [
            'title' => "Welcome to our PDF Test",'evenement' => $evenement
        ]);

        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        $dompdf->stream("mmypdf.pdf", [
            "Attachment" => false
        ]);

        // Send some text response
        return new Response("sd");
    }

    /**
     * @Route("/eventinfo{id}", name="eventinfo")
     */
    public function show(int $id): Response
    {
        $rep=$this->getDoctrine()->getRepository(Evenement::class);
        $entityManager = $this->getDoctrine()->getManager();

        $evenement=$rep->find($id);
        dump($evenement);
        $evenement->setViewed($evenement->getViewed()+1);
        $entityManager->persist($evenement);
        $entityManager->flush();

        return $this->render('evenement_societe/eventinfo.html.twig', [
            'evenement' => $evenement,
        ]);


    }

    /**
     * @Route("/manager", name="manager")
     */
    public function manager(): Response
    {

        $rep=$this->getDoctrine()->getRepository(Evenement::class);
        $evenement=$rep->findAll();


        return $this->render('evenement_societe/evenementmanager.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/sortbytitleasc", name="sortbytitleasc")
     */
    public function sortByTitleASC(): Response
    {

        $rep=$this->getDoctrine()->getRepository(Evenement::class);
        $evenement=$rep->sortByTitleASC();


        return $this->render('evenement_societe/evenementmanager.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/sortbytitledesc", name="sortbytitledesc")
     */
    public function sortByTitleDESC(): Response
    {
        $rep=$this->getDoctrine()->getRepository(Evenement::class);
        $evenement=$rep->sortByTitleDESC();
        return $this->render('evenement_societe/evenementmanager.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/socdeleteevenement{id}", name="socdeleteevenement")
     */
    public function deleteevent(int $id): Response
    {

        $entityManager = $this->getDoctrine()->getManager();
        $event = $entityManager->getRepository(Evenement::class)->find($id);
        $entityManager->remove($event);
        $title = $event->getTitle();

        $notif = new NotifEvent();
        $notif->setNotif('Event '.$title.' Deleted');
        $entityManager->persist($notif);
        $entityManager->flush();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       $entityManager->flush();

        return $this->redirectToRoute("manager");
    }



    /**
     * @Route("/addevent", name="addevent")
     */
    public function AddEvent(Request $request)
    {
        $event= new Evenement();
        $form=$this->createForm(EventType::class,$event);
        $form->add('Add',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $file = $request->files->get('event')['my_picture'];
            $upload_directory = $this->getParameter('upload_directory');
            $filename = md5(uniqid()).'.'.$file->guessExtension();
            $file->move(
                $upload_directory,
                $filename
            );
            $entityManager = $this->getDoctrine()->getManager();
            $notif = new NotifEvent();
            $notif->setNotif('New Event Is Here');
            $entityManager->persist($notif);

            $event->setPicture($filename);

            $entityManager->persist($event);
            $entityManager->flush();
            return $this->redirectToRoute("manager");
        }

        return $this->render('evenement_societe/addevent.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/updateevent{id}", name="updateevent")
     */
    public function UpdateEvent(Request $request,$id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $event = $entityManager->getRepository(Evenement::class)->find($id);

        $form=$this->createForm(EventType::class,$event);
        $form->add('Update',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $title = $event->getTitle();

            $notif = new NotifEvent();
            $notif->setNotif('Event '.$title.' Updated');
            $entityManager->persist($notif);
            //$entityManager->flush();

            $entityManager->flush();
            return $this->redirectToRoute("manager");
        }

        return $this->render('evenement_societe/updateevent.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/searchevenement ", name="searchevenement")
     */
    public function searchevenement(Request $request)
    {
        $repository = $this->getDoctrine()->getRepository(Evenement::class);
        $requestString=$request->get('searchValue');

        $evenement = $repository->findEvenementByTitle($requestString);


        $response = new Response();

        $encoders = array(new XmlEncoder(), new JsonEncode());
        $normalizers = array(new GetSetMethodNormalizer());

        $serializer = new Serializer($normalizers, $encoders);
        $jsonContent = $serializer->serialize($evenement, 'json');
        dump($jsonContent);

        $response->headers->set('Content-Type', 'application/json');
        $response->setContent($jsonContent);


        return $response;
    }

    /**
     * @Route("/notificationuser", name="notificationuser")
     */
    public function notificationuser(): Response
    {

templates/evenement_societe/addevent.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <!--=================================
inner banner -->
    <div class="header-inner bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="text-primary">Add Event</h2>
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="evenementsociete">Home</a></li>
                        <li class="breadcrumb-item active"> <i class="fas fa-chevron-right"></i> <span>Event</span></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--=================================
    inner banner -->
    <hr>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade active show" id="Job-detail" role="tabpanel" aria-labelledby="Job-detail-tab">
            <section class="space-ptb">
                <div class="container">
                    {{ form_start(form) }}
                    {{ form_row(form.title,{ 'attr':{ 'placeholder':"Event Title",'class':"form-control"}}) }}
                    {{ form_row(form.type,{ 'attr':{ 'placeholder':"Type",'class':"form-control"}}) }}
                    {{ form_row(form.description,{ 'attr':{ 'placeholder':"Event Title",'class':"form-control"}}) }}
                    {{ form_row(form.dateAt,{ 'attr':{ 'class':"form-control input-group date"}}) }}

                    <hr>
                    {{ form_row(form.localitation,{ 'attr':{ 'placeholder':"Localisation",'class':"form-control"}}) }}
                    {{ form_row(form.id_societe,{ 'attr':{ 'placeholder':"idsoc",'class':"form-control"}}) }}
                    <hr>
                    {{ form_row(form.my_picture,{ 'attr':{ 'class':"upload-file"}}) }}
                    <hr>
                    {{ form_row(form.Add,{ 'attr':{ 'class':"btn btn-primary"}}) }}
                    {{ form_end(form) }}
                </div>
            </section>
        </div>
    </div>








{% endblock %}

templates/evenement_societe/adminevent.html.twig
{% extends 'basebackadmin.html.twig' %}





{% block body %}
<!--=================================
inner banner -->
<div class="header-inner bg-light text-center">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="text-primary">Manage The Events</h2>
                <ol class="breadcrumb mb-0 p-0">
                    <li class="breadcrumb-item"><a href="evenementsociete">Home</a></li>
                    <li class="breadcrumb-item active"> <i class="fas fa-chevron-right"></i> <span>Events</span></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!--=================================
inner banner -->
<hr>
    <!--=================================
    Manage Candidates -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="user-dashboard-info-box mb-0">
                        <div class="row mb-4">
                            <div class="col-md-7 col-sm-5 d-flex align-items-center">
                                <div class="section-title-02 mb-0 ">
                                    <h4 class="mb-0">Manage Events</h4>
                                </div>
                            </div>

                        </div>
                        <div class="section-title-02 mb-0 ">
                            <a class="btn btn-primary btn-block" href="{{ path('notification')}}">Manage Notifications</a>
                        </div>
                        <hr>
                        <div class="section-title-02 mb-0 ">
                            <a class="btn btn-primary btn-block" href="{{ path('stat')}}">Stat</a>
                        </div>
                        <hr>
                        <div class="section-title-02 mb-0 ">
                            <a class="btn btn-primary btn-block" href="{{ path('sortbytitleascadmin')}}">Sort By Title ASC</a>
                        </div>
                        <br>
                        <div class="section-title-02 mb-0 ">
                            <a class="btn btn-primary btn-block" href="{{ path('sortbytitledescadmin')}}">Sort By Title DESC</a>
                        </div>
                        <hr>
                        <div class="user-dashboard-table table-responsive">
                            <table class="table table-bordered">
                                <thead class="bg-light">
                                <tr >
                                    <th scope="col">Events</th>
                                    <th scope="col">Type</th>
                                    <th scope="col">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for e in evenement %}
                                    <tr>
                                        <th scope="row">{{ e.title }}
                                            <p class="mb-1 mt-2">{{ e.dateAt|date('Y-m-d H:i:s') }}</p>
                                            <p class="mb-0">{{ e.localitation }}</p>
                                        </th>
                                        <td>{{ e.type }}</td>
                                        <td>
                                            <ul class="list-unstyled mb-0 d-flex">
                                                <li><a href="{{ path('gestiondesparticipant',{'id':e.id})}}" class="text-primary" data-toggle="tooltip" title="view"><i class="far fa-eye"></i></a></li>
                                                <li><a href="{{ path('adminevenement',{'id':e.id})}}" class="text-danger" data-toggle="tooltip" title="Delete"><i class="far fa-trash-alt"></i></a></li>
                                            </ul>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--=================================
    Manage Events -->
{% endblock %}

templates/evenement_societe/evenementcard.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<!--=================================
banner -->

<section class="banner bg-holder bg-overlay-black-30" style="background-image: url(images/event.jpg);">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="job-search-field job-search-field-02 search-under-banner">
                    <div class="job-search-item">
                        <form class="form-row basic-select-wrapper">
                            <div class="form-group col-lg col-md-6">
                                <div class="form-group-search">
                                    <label>Event Title</label>
                                    <div class="d-flex align-items-center"><input class="form-control" type="search" placeholder="Title"></div>
                                </div>
                            </div>
                            <div class="form-group col-lg col-md-6">
                                <div class="form-group-search">
                                    <label>Location</label>
                                    <div class="d-flex align-items-center"><input class="form-control" type="search" placeholder="town or country"></div>
                                </div>
                            </div>

                            <div class="form-group col-lg-2 col-md-4">
                                <div class="mt-0">
                                    <button class="btn btn-primary align-items-center" type="submit"><i class="fas fa-search mr-1"></i>Find Events</button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--=================================
banner -->

{% endblock %}

templates/evenement_societe/eventinfo.html.twig
{% extends 'base.html.twig' %}

{% block body %}



    <!--=================================
inner banner -->
    <div class="header-inner bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="text-primary">Event</h2>
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="evenementsociete">Home</a></li>
                        <li class="breadcrumb-item active"> <i class="fas fa-chevron-right"></i> <span>Event</span></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--=================================
    inner banner -->



    <section class="space-ptb">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="employers-list border">
                        <div class="employers-list-logo">
                            <img class="img-fluid" src="images/{{ evenement.picture }}" alt="">
                        </div>
                        <div class="employers-list-details">
                            <div class="employers-list-info">
                                <div class="employers-list-title">
                                    <h5 class="mb-0">{{ evenement.title }}</h5>
                                </div>
                                <div class="employers-list-option">
                                    <ul class="list-unstyled">
                                        <li><i class="fas fa-map-marker-alt pr-1"></i>{{ evenement.localitation }}</li>
                                    </ul>
                                    <ul class="list-unstyled">
                                        <li><i class=""></i>Organized By :{{ evenement.idSociete }}</li>
                                    </ul>
                                    <ul class="list-unstyled">
                                        <li><i class="far fa-check-circle font-md text-primary mr-2"></i>{{ evenement.type }}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="border p-4 mt-4 mt-md-5">
                        <div class="row">
                            <div class="col-md-4 col-sm-6 mb-4">
                                <div class="d-flex">
                                    <i class="font-xll text-primary align-self-center flaticon-binoculars"></i>
                                    <div class="feature-info-content pl-3">
                                        <label class="mb-1">Viewed</label>
                                        <span class="mb-0 font-weight-bold d-block text-dark">{{ evenement.viewed }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-6 mb-4">
                                <div class="d-flex">
                                    <i class="font-xll text-primary align-self-center flaticon-placeholder"></i>
                                    <div class="feature-info-content pl-3">
                                        <label class="mb-1">Locations</label>
                                        <span class="mb-0 font-weight-bold d-block text-dark">{{ evenement.localitation }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-6 mb-4">
                                <div class="d-flex">
                                    <i class="font-xll text-primary align-self-center flaticon-list"></i>
                                    <div class="feature-info-content pl-3">
                                        <label class="mb-1">Type</label>
                                        <span class="mb-0 font-weight-bold d-block text-dark">{{ evenement.type }}</span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="mt-4 mt-md-5 mb-4 mb-md-5">
                        <h5 class="mb-3 mb-md-4">Description</h5>
                        <p>{{ evenement.description }}</p>

                    </div>
                    <hr>

                </div>
                <!--=================================
                sidebar -->
                <div class="col-lg-4 mt-4 mt-lg-0">
                    <div class="sidebar mb-0">
                        <div class="widget">
                            <div class="company-detail-meta justify-content-start">
                                <ul class="list-unstyled">
                                    <li>
                                        <div class="share-box">
                                            <a href="#"> <i class="fas fa-share-alt"></i><span class="pl-2">Share</span></a>
                                            <ul class="list-unstyled share-box-social">
                                                <li> <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/hand.calsp"><i class="fab fa-facebook-f"></i></a> </li>

                                            </ul>
                                        </div>
                                    </li>

                                    <li>
                                        <a href="{{path('pdf',{'id':evenement.id})}}"><i class="fas fa-file-pdf"></i><span class="pl-2">Print PDF</span></a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="widget">
                            <div class="widget-title">
                                <a class="btn btn-primary btn-block" href="{{ path('participant_e',{'id':evenement.id})}}"><i class="far fa-paper-plane"></i>Participate</a>
                            </div>

                        </div>
                    </div>
                </div>
                <!--=================================
                sidebar -->
            </div>
        </div>
    </section>



{% endblock %}

templates/evenement_societe/eventmail.html.twig
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: powderblue;
        }
        h1 {
            color: blue;
            font-family: verdana;
            font-size: 150%;
            padding-left: 10px;

        }
        h2 {
            color: red;
            font-family: verdana;
            font-size: 300%;
            padding-left: 220px;

        }
        p {
            color: red;
            font-family: courier;
            font-size: 100%;
            padding-left: 20px;
        }
        a {
            padding-left: 20px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>
<body>


<h2>Hand Clasp</h2>
<br>
<br>
<br>
<br><br>
<br>
<h1>Event Name : {{ evenement.title }}</h1>
<br>
<br>
<p>Localisation : {{ evenement.localitation }}</p>
<br>
<br>
<p>Type :{{ evenement.type }}</p>
<br>
<br>
<p>Description :{{ evenement.description }}</p>
<br>
<br>
<p>Viwed par :{{ evenement.viewed }}</p>
<br>
<br><br>
<br><br>
<br><br>
<br>
<br><br>
<br>
<br><br>
<br>
<hr>
<a>You Can Find Us On Facebook : https://www.facebook.com/hand.calsp</a>
<br>
<a>You Can Find Us On Instagram : https://www.instagram.com/hand_clasp</a>
<hr>

</body>
</html>

templates/evenement_societe/participant.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <!--=================================
inner banner -->
    <div class="header-inner bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="text-primary">Participate</h2>
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="evenementsociete">Home</a></li>
                        <li class="breadcrumb-item active"> <i class="fas fa-chevron-right"></i> <span>Events</span></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--=================================
    inner banner -->
                    {{ form_start(form) }}
{% endblock %}

templates/evenement_societe/participationmail.html.twig
<h4>Participation Confirmed</h4>