src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)

 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"emailadresse"},
 * message="Already used")
 */

class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    public $Username;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    public $tax_registration_number;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    private $localisation;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    private $images; //fhmt chy chsar crash

    /**
     * @ORM\Column(type="string", length=240, nullable=true)

     * @Assert\Length(min="8",minMessage="your password must be at least 8 characters long")
     * @Assert\EqualTo(propertyPath="confirm_password",message="
    you did not type the same password")
     */

    private $password;
    /**

     * @Assert\EqualTo(propertyPath="password",message="
    you did not type the same password")
     */
    public $confirm_password;

    /**
     * @ORM\Column(type="integer", nullable=true)

     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     * @Assert\Email (
     *     message = "The emailadresse '{{ value }}' is not a valid emailadresse."
     * )

     */


    private $emailadresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)

     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)

     */
    private $cin;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=240, nullable=true)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setNameCompany(?string $Username): self
    {
        $this->Username= $Username;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTaxRegistrationNumber(): ?string
    {
        return $this->tax_registration_number;
    }

    public function setTaxRegistrationNumber(?string $tax_registration_number): self
    {
        $this->tax_registration_number = $tax_registration_number;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->localisation;
    }

    public function setLocalisation(?string $localisation): self
    {
        $this->localisation = $localisation;

        return $this;
    }

    public function getImages(): ?string
    {
        return $this->images;
    }

    public function setImages(?string $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }

    public function setNumero(?int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getEmailadresse(): ?string
    {
        return $this->emailadresse;
    }

    public function setEmailadresse(?string $emailadresse): self
    {
        $this->emailadresse = $emailadresse;

        return $this;
    }



    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(?string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
    public function getRoles()
    {
        return['role'];
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Username')
            ->add('description')
            ->add('tax_registration_number')
            ->add('localisation')

            ->add('images',FileType::class,[
                'mapped'=>false,
            ])
            ->add('password',PasswordType::class)
            ->add('confirm_password',PasswordType::class)
            ->add('numero')
            ->add('emailadresse')

            ->add('role',ChoiceType::class,[

                'required'=> true,
                'expanded' => false,
                'multiple' => false,
                'choices'=>[
                    'job seeker'=>'job seeker',
                    'company'=>'company',

                ],
                'data'=>'company',
                'label'=>'role'
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/USERController.php
<?php

namespace App\Controller;

use App\Entity\NotifEvent;

use App\Entity\NotifUser;
use App\Entity\User;
use App\Form\WorkreseacherType;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
use App\Form\UserType;
use App\Repository\UserRepository;
use phpDocumentor\Reflection\DocBlock\Serializer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\Routing\Loader\XmlFileLoader;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Serializer\Encoder\JsonEncode;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;
use Dompdf\Dompdf;
use Dompdf\Options;
class USERController extends AbstractController
{

    /**
     * @Route("/signup", name="app_register")
     */
    public function  signupAction(Request  $request, UserPasswordEncoderInterface $passwordEncoder) {

        $emailadresse = $request->query->get("emailadresse");
        $Username = $request->query->get("Username");
        $password = $request->query->get("password");
        $role= $request->query->get("role");


        //control al email lazm @
        if(!filter_var($emailadresse, FILTER_VALIDATE_EMAIL)) {
            return new Response("email invalid.");
        }
        $user = new User();
        $user->setUsername($username);
        $user->setsetEmailadresse($emailadresse);
        $pass = $passwordEncoder->encodePassword(
            $user,
            $password
        );

        $user->setIsVerified(true);//par défaut user lazm ykoun enabled.

        $user->setRole($role);//aleh array khater roles par defaut fi security  type ta3ha array

        try {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return new JsonResponse("success",200);//200 ya3ni http result ta3 server OK
        }catch (\Exception $ex) {
            return new Response("execption ".$ex->getMessage());
        }
    }


    /**
     * @Route("signin", name="app_login")
     */

    public function signinAction(Request $request) {
        $Username = $request->query->get("Username");
        $password = $request->query->get("password");

        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(User::class)->findOneBy(['Username'=>$Username]);//bch nlawj ala user b username ta3o fi base s'il existe njibo
        //ken l9ito f base
        if($user){
            //lazm n9arn password zeda madamo crypté nesta3mlo password_verify
            if(password_verify($password,$user->getPassword())) {
                $serializer = new Serializer([new ObjectNormalizer()]);
                $formatted = $serializer->normalize($user);
                return new JsonResponse($formatted);
            }
            else {
                return new Response("passowrd not found");
            }
        }
        else {
            return new Response("failed");//ya3ni username/pass mch s7a7

        }
    }


    /**
     * @Route("user/ediUser", name="app_gestion_profile")
     */

    public function editUser(Request $request, UserPasswordEncoderInterface $passwordEncoder) {
        $id = $request->get("id");//kima query->get wala get directement c la meme chose
        $Username = $request->query->get("Username");
        $password = $request->query->get("password");
        $emailadresse = $request->query->get("emailadresse");
        $em=$this->getDoctrine()->getManager();
        $user = $em->getRepository(User::class)->find($id);
        //bon l modification bch na3mlouha bel image ya3ni kif tbadl profile ta3ik tzid image
        if($request->files->get("images")!= null) {

            $file = $request->files->get("images");//njib image fi url
            $fileName = $file->getClientOriginalName();//nom ta3ha

            //taw na5ouha w n7otaha fi dossier upload ely tet7t fih les images en principe te7t public folder
            $file->move(
                $fileName
            );
            $user->setImages($fileName);
        }


        $user->setUsername($username);
        $user->setPassword(
            $passwordEncoder->encodePassword(
                $user,
                $password
            )
        );

        $user->setEmailadresse($emailadresse);
        $user->setIsVerified(true);//par défaut user lazm ykoun enabled.



        try {
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return new JsonResponse("success",200);//200 ya3ni http result ta3 server OK
        }catch (\Exception $ex) {
            return new Response("fail ".$ex->getMessage());
        }

    }

    /**
     * @Route("/notificationn", name="notificationn")
     */
    public function notificationn(): Response
    {

        $rep=$this->getDoctrine()->getRepository(NotifUser::class);
        $notif=$rep->findAll();


        return $this->render('user/notiff.html.twig', [
                'notif' => $notif,
            ]
        );

    }

    /**
     * @Route("/searchecompany ", name="searchecompany")
     */
    public function searchecompany(Request $request)
    {
        $repository = $this->getDoctrine()->getRepository(User::class);
        $requestString=$request->get('searchValue');

        $company = $repository->findEvenementByname($requestString);



        $response = new Response();

        $encoders = array(new XmlEncoder(), new JsonEncode());
        $normalizers = array(new GetSetMethodNormalizer());

        $serializer = new \Symfony\Component\Serializer\Serializer($normalizers, $encoders);
        $jsonContent = $serializer->serialize($company, 'json');

        $response->headers->set('Content-Type', 'application/json');
        $response->setContent($jsonContent);
        dump($jsonContent);


        return $response;
    }
    /**
     * @Route("/u/s/e/r", name="u_s_e_r")
     */
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'USERController',
        ]);
    }
    /**
     * @Route("/lol1", name="lol1")
     */
    public function manager(): Response
    {

        $rep=$this->getDoctrine()->getRepository(User::class);
        $user=$rep->findAll();



        return $this->render('user/companymanager.html.twig', [
            'user' => $user,
        ]);
    }
    /**
     * @Route("/usera", name="usera")
     */
    public function new1(Request $request)
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->add('save',SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $request->files->get('user')['images'];

            $upload_directory = $this->getParameter('upload_directory');
            $filename = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move(
                $upload_directory,
                $filename
            );
            $user->setImages($filename);
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('lol1');

        }
        return $this->render('user/ajoutmanager.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    /** //
     *
     * @Route("/yahala", name="yahala")
     */
    public function index2(): Response
    {
        return $this->render('user/yahala.html.twig', [
            'controller_name' => 'USERController',
        ]);
    }
    /**
     * @Route("/userfront", name="userfront")
     */
    public function newfront(Request $request,UserPasswordEncoderInterface $encoder)
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->add('save',SubmitType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file=$form->get('images')->getData();
            $upload_directory = $this->getParameter('upload_directory');
            $filename = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move(
                $upload_directory,
                $filename
            );
            $user->setImages($filename);
            $entityManager = $this->getDoctrine()->getManager();
            $hash =$encoder->encodePassword($user,$user->getPassword());
            $user->setPassword($hash);
            $notif = new NotifUser();
            $notif->setNotifuser('New User');
            $entityManager->persist($notif);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            //mailing
            $mail = new PHPMailer(true);

            try {

                $Username = $form->get('Username')->getData();

                $description = $form->get('description')->getData();
                $localisation = $form->get('localisation')->getData();
                $numero = $form->get('numero')->getData();
                $email = $form->get('emailadresse')->getData();


                //Server settings
                $mail->SMTPDebug = SMTP::DEBUG_SERVER;
                $mail->isSMTP();
                $mail->Host       = 'smtp.gmail.com';
                $mail->SMTPAuth   = true;
                $mail->Username   = 'faroukgasaraa@gmail.com';             // SMTP username
                $mail->Password   = 'farouk1998';                               // SMTP password

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('company_delete', {'id':user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
<!--=================================
Register -->
<section class="space-ptb">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-10 col-md-12">
                <div class="login-register">
                    <div class="section-title">
                        <h4 class="text-center">Create Your Account</h4>
                    </div>
                    <fieldset>
                        <legend class="px-2">Choose your Account Type</legend>
                        <ul class="nav nav-tabs nav-tabs-border d-flex" role="tablist">
                            <li class="nav-item mr-4">
                                <a class="nav-link active"  data-toggle="tab" href="#candidate" role="tab" >
                                    <div class="d-flex">
                                        <div class="tab-icon">
                                            <i class="flaticon-users"></i>
                                        </div>
                                        <div class="ml-3">
                                            <h6 class="mb-0">Company</h6>
                                            <p class="mb-0">I want to discover companies.</p>
                                        </div>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </fieldset>
                    <div class="tab-content">
                        <div class="tab-pane active" id="candidate" role="tabpanel">

                            {{ form_start(form) }}

                            <div class="g-recaptcha" data-sitekey="6LezZHoaAAAAADzHuijwpBNJZfKeaydmQaLw25wC"></div>


                            {{ form_end(form) }}


                        </div>

                    </div>
                    <div class="mt-4">
                        <fieldset>
                            <legend class="px-2">Login or Sign up with</legend>
                            <div class="social-login">
                                <ul class="list-unstyled d-flex mb-0">
                                    <li class="facebook text-center">
                                        <a href="#"> <i class="fab fa-facebook-f mr-4"></i>Login with Facebook</a>
                                    </li>
                                    <li class="twitter text-center">
                                        <a href="#"> <i class="fab fa-twitter mr-4"></i>Login with Twitter</a>
                                    </li>
                                    <li class="google text-center">
                                        <a href="#"> <i class="fab fa-google mr-4"></i>Login with Google</a>
                                    </li>
                                    <li class="linkedin text-center">
                                        <a href="#"> <i class="fab fa-linkedin-in mr-4"></i>Login with Linkedin</a>
                                    </li>
                                </ul>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</section>

templates/user/ajoutmanager.html.twig
{% extends 'basebackadmin.html.twig' %}
{% block body %}
    <section class="space-ptb">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-10 col-md-12">
                    <div class="login-register">
                        <div class="section-title">
                            <h4 class="text-center">Create Your Account</h4>
                        </div>
                        <fieldset>
                            <legend class="px-2">Choose your Account Type</legend>
                            <ul class="nav nav-tabs nav-tabs-border d-flex" role="tablist">
                                <li class="nav-item mr-4">
                                    <a class="nav-link active"  data-toggle="tab" href="#candidate" role="tab" >
                                        <div class="d-flex">
                                            <div class="tab-icon">
                                                <i class="flaticon-users"></i>
                                            </div>
                                            <div class="ml-3">
                                                <h6 class="mb-0">Company</h6>
                                                <p class="mb-0">I want to discover companies.</p>
                                            </div>
                                        </div>
                                    </a>
                                </li>

                            </ul>
                        </fieldset>
                        <div class="tab-content">
                            <div class="tab-pane active" id="candidate" role="tabpanel">
                                {{ form_start(form) }}
                                {{ form_row(form.Username,{ 'attr':{ 'placeholder':"name of company",'class':"form-control"}}) }}
                                {{ form_row(form.description,{ 'attr':{ 'placeholder':"describe the function of the company",'class':"form-control"}}) }}
                                {{ form_row(form.tax_registration_number,{ 'attr':{ 'placeholder':"your tax number please for the security",'class':"form-control"}}) }}



                                {{ form_row(form.localisation,{ 'attr':{ 'placeholder':"where is your company?",'class':"form-control"}}) }}
                                {{ form_row(form.numero,{ 'attr':{ 'placeholder':"your phone number please",'class':"form-control"}}) }}
                                {{ form_row(form.images,{ 'attr':{ 'class':"upload-file"}}) }}
                                {{ form_row(form.emailadresse,{ 'attr':{ 'placeholder':"your email adress please",'class':"form-control"}})}}
                                {{ form_row(form.password,{ 'attr':{ 'placeholder':"choose your password",'class':"form-control"}})}}
                                {{ form_row(form.save,{ 'attr':{ 'class':"btn btn-primary"}}) }}
                                {{ form_end(form) }}
                            </div>

                        </div>

                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

templates/user/edit.html.twig
{% extends 'basebackadmin.html.twig' %}


{% block body %}
    <h1>Edit Company</h1>

    {{ include('user/formm.html.twig', {'button_label': 'Update'}) }}

    <a> href="{{ path('company_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/editm.html.twig
{% extends 'basebackadmin.html.twig' %}


{% block body %}
    <h1>Edit Company</h1>

    {{ include('company/formm.html.twig', {'button_label': 'Update'}) }}


    <a> href="{{ path('company_index') }}">back to list</a>

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}

templates/user/formm.html.twig
<!--=================================
Register -->
<section class="space-ptb">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-10 col-md-12">
                <div class="login-register">
                    <div class="section-title">
                        <h4 class="text-center">Create Your Account</h4>
                    </div>
                    <fieldset>
                        <legend class="px-2">Choose your Account Type</legend>
                        <ul class="nav nav-tabs nav-tabs-border d-flex" role="tablist">
                            <li class="nav-item mr-4">
                                <a class="nav-link active"  data-toggle="tab" href="#candidate" role="tab" >
                                    <div class="d-flex">
                                        <div class="tab-icon">
                                            <i class="flaticon-users"></i>
                                        </div>
                                        <div class="ml-3">
                                            <h6 class="mb-0">Company</h6>
                                            <p class="mb-0">I want to discover companies.</p>
                                        </div>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </fieldset>
                    <div class="tab-content">
                        <div class="tab-pane active" id="candidate" role="tabpanel">
                            {{ form_start(form) }}



                            {{ form_end(form) }}

                        </div>

                    </div>

                    </fieldset>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<!--=================================
Register -->

templates/user/new.html.twig
{% extends 'base.html.twig' %}


{% block body %}



    {{ include('user/_form.html.twig') }}


{% endblock %}

templates/user/notiff.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!--=================================
inner banner -->
    <div class="header-inner bg-light text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="text-primary">Notifications</h2>
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="evenementsociete">Home</a></li>
                        <li class="breadcrumb-item active"> <i class="fas fa-chevron-right"></i> <span>Notifications</span></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--=================================
    inner banner -->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="user-dashboard-info-box mb-0 pb-4">
                        <div class="section-title-02 mb-4">
                            <h4>Notifications</h4>
                        </div>
                        <div class="row">
                            {% for e in notif %}
                                <div class="col-12">
                                    <div class="job-list ">

                                        <div class="job-list-logo">
                                            <img class="img-fluid" src="images/svg/82-821023_youtube-bell-png-youtube-notification-bell-png-clipart.png" alt="">
                                        </div>
                                        <div class="job-list-details">
                                            <div class="job-list-info">
                                                <div class="job-list-title">
                                                    <h5 class="mb-0"><a href="">{{ e.notifuser }}</a></h5>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/user/show.html.twig
{% extends 'basebackadmin.html.twig' %}



{% block body %}
    <h1>Company</h1>

    <table class="table">
        <tbody>
        <tr>

            <th>Id</th>
            <td>{{ user.id }}</td>
        </tr>
        <tr>
            <th>Name_company</th>
            <td>{{ user.Username }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ user.description }}</td>
        </tr>
        <tr>
            <th>Tax registration number</th>
            <td>{{ user.taxRegistrationNumber }}</td>
        </tr>
        <tr>
            <th>location</th>
            <td>{{ user.localisation}}</td>
        </tr>
        <tr>
            <th>phone number</th>
            <td>{{ user.numero }}</td>
        </tr>
        <tr>
            <th>logo</th>
            <td>{{ user.images }}</td>
        </tr>
        <tr>
            <th>Email Adress</th>
            <td>{{ user.emailadresse }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ user.password }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('companyeditm', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}


{% endblock %}